// <auto-generated />
using System;
using KelCVBajaDivaManufaktur.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KelCVBajaDivaManufaktur.Migrations
{
    [DbContext(typeof(KelCVBajaDivaManufakturContext))]
    [Migration("20250830174436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KelCVBajaDivaManufaktur.Models.BahanBaku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NamaBahan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("BahanBaku");
                });

            modelBuilder.Entity("KelCVBajaDivaManufaktur.Models.Pengguna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HakAkses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPengguna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pengguna");
                });

            modelBuilder.Entity("KelCVBajaDivaManufaktur.Models.PesanBB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BahanBakuId")
                        .HasColumnType("int");

                    b.Property<string>("SatuanBB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StokBB")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BahanBakuId");

                    b.HasIndex("SupplierId");

                    b.ToTable("PesanBB");
                });

            modelBuilder.Entity("KelCVBajaDivaManufaktur.Models.Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GambarProduk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kategori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaProduk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Produk");
                });

            modelBuilder.Entity("KelCVBajaDivaManufaktur.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaSupplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoHP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("KelCVBajaDivaManufaktur.Models.Transaksi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaraBayar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Jumlah")
                        .HasColumnType("int");

                    b.Property<string>("NamaPelanggan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdukId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TanggalBeli")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalBayar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdukId");

                    b.ToTable("Transaksi");
                });

            modelBuilder.Entity("KelCVBajaDivaManufaktur.Models.BahanBaku", b =>
                {
                    b.HasOne("KelCVBajaDivaManufaktur.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("KelCVBajaDivaManufaktur.Models.PesanBB", b =>
                {
                    b.HasOne("KelCVBajaDivaManufaktur.Models.BahanBaku", "BahanBaku")
                        .WithMany()
                        .HasForeignKey("BahanBakuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KelCVBajaDivaManufaktur.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BahanBaku");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("KelCVBajaDivaManufaktur.Models.Transaksi", b =>
                {
                    b.HasOne("KelCVBajaDivaManufaktur.Models.Produk", "Produk")
                        .WithMany()
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produk");
                });
#pragma warning restore 612, 618
        }
    }
}
